name: Firestore Backups
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Backup'
        default: 'Backup'
        required: false
  schedule:
    - cron: '*/5 * * * *'
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - run: gcloud config set project web-form-f50fd
      - run: gcloud firestore export gs://web-form-f50fd.appspot.com
